post:
  x-eov-operation-id: createVariable
  x-eov-operation-handler: v1/handlers/variables/variables.handler
  tags:
    - Variables
  summary: Create a variable
  description: Create a variable in your instance.
  requestBody:
    description: Created variable object.
    content:
      application/json:
        schema:
          $ref: '../schemas/variable.yml'
    required: true
  responses:
    '201':
      description: A variable object
      content:
        application/json:
          schema:
            $ref: '../schemas/variable.yml'
    '400':
      $ref: '../../../../shared/spec/responses/badRequest.yml'
    '409':
      $ref: '../../../../shared/spec/responses/conflict.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
get:
  x-eov-operation-id: getVariables
  x-eov-operation-handler: v1/handlers/variables/variables.handler
  tags:
    - Variables
  summary: Retrieve variables
  description: Retrieve variables from your instance.
  parameters:
    - $ref: '../../../../shared/spec/parameters/limit.yml'
    - $ref: '../../../../shared/spec/parameters/cursor.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/variableList.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
