apiVersion: v1
kind: Secret
metadata:
  name: staging-n8n-secrets
  namespace: staging
type: Opaque
data:
  DB_POSTGRESDB_HOST: cGdtLXVmNjRmeTU3NTFjaDYyOTQxNDgzMC5wZy5yZHMuYWxpeXVuY3MuY29t
  DB_POSTGRESDB_USER: b2Ffc3RhZ2luZ19uOG4=
  DB_POSTGRESDB_PASSWORD: b1VLVVRab3Q2WHBBVUpaZA==
  N8N_BASIC_AUTH_USER: b2FuOG5iYXNpYw==
  N8N_BASIC_AUTH_PASSWORD: YkdWeENveEUzN1VpNTdlMg==
  X_HASURA_ADMIN_SECRET: Z1dXZmhwZHEyeFlsYnNyNw==
