vscode:
  extensions:
    - coenraads.bracket-pair-colorizer-2 
    - pustelto.bracketeer
    - formulahendry.auto-close-tag

tasks:
  - init: npm install -g lerna  && lerna bootstrap --hoist 
    command: export VUE_APP_URL_BASE_API=$GITPOD_WORKSPACE_URL && npm run dev

# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
