get:
  x-eov-operation-id: getTags
  x-eov-operation-handler: v1/handlers/tags/tags.handler
  tags:
    - Tag
  summary: Retrieve all tags
  description: Retrieve all tags from your instance.
  parameters:
    - $ref: '../../../../shared/spec/parameters/limit.yml'
    - $ref: '../../../../shared/spec/parameters/cursor.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/tagList.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '404':
      $ref: '../../../../shared/spec/responses/notFound.yml'
