apiVersion: v1
kind: Secret
metadata:
  name: prod-n8n-secrets
  namespace: prod
type: Opaque
data:
  DB_POSTGRESDB_HOST: cGdtLXVmNnI4NzI1aGZtdGIwOXAxMTczOTAucGcucmRzLmFsaXl1bmNzLmNvbQ==
  DB_POSTGRESDB_USER: cHJvZF9uOG4=
  DB_POSTGRESDB_PASSWORD: S3kwUDZ6RjNEd3BZUHRObA==
  N8N_BASIC_AUTH_USER: bjhuYmFzaWM=
  N8N_BASIC_AUTH_PASSWORD: M3lQcW4xRDdNRHJhNDd2bA==
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prod-n8n
  name: prod-n8n-svc
  namespace: prod
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  selector:
    app: prod-n8n
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-n8n
  name: prod-n8n
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-n8n
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prod-n8n
    spec:
      volumes:
        - name: prod-n8n-data-pvc
          persistentVolumeClaim:
            claimName: prod-n8n-data-pvc
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/cgp-application/n8n:GIT_TAG
        imagePullPolicy: IfNotPresent
        name: prod-n8n
        env:
        - name: DB_TYPE
          value: "postgresdb"
        - name: DB_POSTGRESDB_DATABASE
          value: "prod_n8n"
        - name: HASURA_URL
          value: "prod-hasura-svc:80"
        - name: DB_POSTGRESDB_HOST
          valueFrom: 
            secretKeyRef: 
              name: prod-n8n-secrets
              key: DB_POSTGRESDB_HOST
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: DB_POSTGRESDB_USER
          valueFrom: 
            secretKeyRef: 
              name: prod-n8n-secrets
              key: DB_POSTGRESDB_USER
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: prod-n8n-secrets
              key: DB_POSTGRESDB_PASSWORD
        - name: N8N_BASIC_AUTH_USER
          valueFrom: 
            secretKeyRef: 
              name: prod-n8n-secrets
              key: N8N_BASIC_AUTH_USER
        - name: N8N_BASIC_AUTH_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: prod-n8n-secrets
              key: N8N_BASIC_AUTH_PASSWORD
        - name: GENERIC_TIMEZONE
          value: "Asia/Shanghai"
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 5678
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: prod-n8n-data-pvc
          mountPath: /home/node/.n8n
