apiVersion: v1
kind: Secret
metadata:
  name: prod-n8n-secrets
  namespace: prod
type: Opaque
data:
  DB_POSTGRESDB_HOST: cGdtLXVmNnI4NzI1aGZtdGIwOXAxMTczOTAucGcucmRzLmFsaXl1bmNzLmNvbQ==
  DB_POSTGRESDB_USER: cHJvZF9uOG4=
  DB_POSTGRESDB_PASSWORD: S3kwUDZ6RjNEd3BZUHRObA==
  N8N_BASIC_AUTH_USER: bjhuYmFzaWM=
  N8N_BASIC_AUTH_PASSWORD: M3lQcW4xRDdNRHJhNDd2bA==
