required:
  - name
  - type
  - data
type: object
properties:
  id:
    type: number
    readOnly: true
    example: 42
  name:
    type: string
    example: Joe's Github Credentials
  type:
    type: string
    example: github
  createdAt:
    type: string
    format: date-time
    readOnly: true
    example: '2022-04-29T11:02:29.842Z'
  updatedAt:
    type: string
    format: date-time
    readOnly: true
    example: '2022-04-29T11:02:29.842Z'
