
get:
  x-eov-operation-id: getCredentialType
  x-eov-operation-handler: v1/handlers/credentials/credentials.handler
  tags:
    - Credential
  summary: Retrieve credential type by ID
  parameters:
    - name: id
      in: path
      description: The credential type ID that you need to retrive
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            type: object
          examples:
            freshdeskApi:
              value:
                additionalProperties: false
                type: 'object'
                properties: {
                  apiKey: {
                    type: 'string'
                  },
                  domain: {
                    type: "string"
                  }
                }
                required: ['apiKey', 'domain']
            slackOAuth2Api:
              value:
                additionalProperties: false
                type: 'object'
                properties: {
                  clientId: {
                    type: 'string'
                  },
                  clientSecret: {
                    type: 'string'
                  }
                }
                required: ['clientId', 'clientSecret']
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '../../../../shared/spec/schemas/error.yml'
    '404':
      description: Credential type not found
