post:
  x-eov-operation-id: createCredential
  x-eov-operation-handler: v1/handlers/credentials/credentials.handler
  tags:
    - Credential
  summary: Create a credential
  description: Creates a credential that can be used by nodes of the specified type.
  requestBody:
    description: Credential to be created.
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/credential.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/credential.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '415':
      description: Unsupported media type.
get:
  x-eov-operation-id: getCredentials
  x-eov-operation-handler: v1/handlers/credentials/credentials.handler
  tags:
    - Credential
  summary: Retrieve metadata on all credentials
  description: Retrieve all credentials from your instance, excluding any secrets.
  parameters:
    - $ref: '../../../../shared/spec/parameters/limit.yml'
    - $ref: '../../../../shared/spec/parameters/cursor.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/credentialList.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
