name: detailsFieldFormat
in: query
description: The format in which to return the data of the execution (in the 'details' field).
required: false
schema:
  type: string
  enum: ['empty', 'flattened', 'json']
