apiVersion: v1
kind: Secret
metadata:
  name: prod-n8n-secrets
  namespace: prod
type: Opaque
data:
  DB_POSTGRESDB_HOST: cGdtLXVmNmZpMTd5NTNmdzlyN2oxNDI4OTAucGcucmRzLmFsaXl1bmNzLmNvbQ==
  DB_POSTGRESDB_USER: cHJvZF9uOG4=
  DB_POSTGRESDB_PASSWORD: R3dUemVQc1ZWMzZLWUNXUQ==
  N8N_BASIC_AUTH_USER: b2FuOG5iYXNpYw==
  N8N_BASIC_AUTH_PASSWORD: M21sQ044Rk1NNlNoWTdISw==
  X_HASURA_ADMIN_SECRET: a09EeDhvVFBuVXZHU013aA==
