apiVersion: v1
kind: Service
metadata:
  labels:
    app: prod-n8n
  name: prod-n8n-svc
  namespace: prod
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  selector:
    app: prod-n8n
  type: ClusterIP
