apiVersion: v1
kind: Secret
metadata:
  name: staging-n8n-secrets
  namespace: staging
type: Opaque
data:
  DB_POSTGRESDB_HOST: cGdtLXVmNnI4NzI1aGZtdGIwOXAxMTczOTAucGcucmRzLmFsaXl1bmNzLmNvbQ==
  DB_POSTGRESDB_USER: c3RhZ2luZ19uOG4=
  DB_POSTGRESDB_PASSWORD: QVNENXhMY0JOY0hLb2JIVg==
  N8N_BASIC_AUTH_USER: bjhuYmFzaWM=
  N8N_BASIC_AUTH_PASSWORD: M3lQcW4xRDdNRHJhNDd2bA==
