apiVersion: v1
kind: Service
metadata:
  labels:
    app: staging-n8n
  name: staging-n8n-svc
  namespace: staging
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  selector:
    app: staging-n8n
  type: ClusterIP
