apiVersion: v1
kind: Service
metadata:
  labels:
    app: staging-hasura
  name: staging-hasura-svc
  namespace: staging
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: staging-hasura
  type: ClusterIP
