name: Benchmark

on:
  pull_request:
    paths:
      - 'packages/cli/**'
      - 'packages/core/**'
      - 'packages/workflow/**'
  workflow_dispatch:

jobs:
  postgres-setup:
    name: Postgres Setup
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DB_POSTGRESDB_PASSWORD: password
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: n8n-io/n8n
          ref: ${{ inputs.ref }}

      - name: Start Postgres
        uses: isbang/compose-action@v2.0.0
        with:
          compose-file: ./.github/docker-compose.yml
          services: postgres

  benchmark-setup:
    name: Benchmark Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: n8n-io/n8n
          ref: ${{ inputs.ref }}

      - run: corepack enable

      - name: Use Node.js ${{ inputs.nodeVersion }}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ inputs.cacheKey == '' }}
        run: pnpm build

      - name: Restore cached build artifacts
        if: ${{ inputs.cacheKey != '' }}
        uses: actions/cache/restore@v4.0.0
        with:
          path: ./packages/**/dist
          key: ${{ inputs.cacheKey }}

      - name: Build benchmark
        working-directory: packages/cli
        run: pnpm build:benchmark

  benchmark:
    needs: [postgres-setup, benchmark-setup]
    runs-on: ubuntu-latest
    steps:
      - name: Benchmark
        uses: CodSpeedHQ/action@v2
        with:
          working-directory: packages/cli
          run: |
            pnpm benchmark:sqlite
            pnpm benchmark:postgres
