name: Test Pull Requests

on: [pull_request]

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      # https://www.notion.so/n8n/Release-Process-fce65faea3d5403a85210f7e7a60d0f8
      - uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(feat|fix|perf|test|docs|refactor|build|ci)'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          error: 'One of the commit titles in the PR should be reworded, see release process docs'

  build:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install -g npm@latest
          npm install
          npm run build --if-present
          npm test
          npm run lint
        env:
          CI: true

