name: PR E2E (skip with label skip-e2e)
run-name: 'E2E tests: ${{ github.event.pull_request.head.ref }}'

on:
  pull_request_review:
    types: [submitted]
    branch:
      - 'master'

jobs:
  runTests:
    name: 'Run E2E tests'
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'approved' && !contains(github.event.pull_request.labels.*.name, 'skip-e2e') }}

    timeout-minutes: 40

    steps:
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test E2E
        run: |
          pnpm cypress:install
          pnpm test:e2e:all

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            cypress/screenshots
          retention-days: 1
