name: End-to-End tests
run-name: E2E Tests on branch ${{ github.event.inputs.branch }}

on:
  pull_request_review:
    types: [submitted]
    branch:
      - 'master'

jobs:
  cancel:
    name: 'Cancel previous runs'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  ifNotApproved:
    name: 'Cancel if PR is not approved'
    if: github.event.review.state != 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/cancel-action@0.2

  runTests:
    name: 'Run E2E tests'
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'skip-e2e')!

    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test E2E
        run: |
          pnpm cypress:install
          pnpm test:e2e:all

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            cypress/screenshots
          retention-days: 1
