name: Test Master (plus)

on:
  push:
    branches:
      - plus

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=4096'

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 20.x

      - name: Setup corepack and pnpm
        run: |
          npm i -g corepack@0.31
          corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup build cache
        uses: useblacksmith/caching-for-turbo@v1

      - name: Build
        run: pnpm build

      - name: Cache build artifacts
        uses: useblacksmith/cache/save@v5
        with:
          path: ./packages/**/dist
          key: ${{ github.sha }}-base:build

  unit-test:
    name: Unit tests
    uses: ./.github/workflows/units-tests-reusable.yml
    needs: install-and-build
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.4]
    with:
      ref: ${{ inputs.branch }}
      nodeVersion: ${{ matrix.node-version }}
      cacheKey: ${{ github.sha }}-base:build
      collectCoverage: ${{ matrix.node-version == '20.x' }}
      ignoreTurboCache: ${{ matrix.node-version == '20.x' }}
      skipFrontendTests: ${{ matrix.node-version != '20.x' }}

  lint:
    name: Lint
    uses: ./.github/workflows/linting-reusable.yml
    needs: install-and-build
    with:
      ref: ${{ inputs.branch }}
      cacheKey: ${{ github.sha }}-base:build
