name: Upload Sentry Source Maps

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version to upload source maps for'
        required: true


jobs:
  upload-sourcemaps:
    name: Upload Source Maps to Sentry
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.event.release.tag_name || github.event.inputs.release }}

    steps:
      - uses: actions/checkout@v4.1.1
        ref: tags/n8n@${{ env.RELEASE }}

      - run: corepack enable
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup build cache
        uses: rharkor/caching-for-turbo@v1.5

      - name: Build
        run: pnpm build

      - name: Cache build artifacts
        uses: actions/cache/save@v4.0.0
        with:
          path: ./packages/**/dist
          key: ${{ github.sha }}-base:build

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ env.RELEASE }}
          sourcemaps: packages/editor-ui/dist/
