name: Runs unit tests for a given ref

on:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: 'GitHub ref to test.'
        required: true
        type: string
      nodeVersion:
        description: 'Version of node to use.'
        required: false
        type: string
        default: '18.x'
      prNumber:
        description: 'PR number to run tests for.'
        required: false
        type: number

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Compute branch
        id: compute-branch
        run: |
          BRANCH_NAME=""
          if [[ "${{ inputs.prNumber }}" != "" && "${{ inputs.prNumber }}" != "null" ]]; then
            BRANCH_NAME="refs/pull/${{ inputs.prNumber }}/merge"
          else
            BRANCH_NAME="${{ inputs.ref }}"
          fi
          echo "::set-output name=branch::$BRANCH_NAME"

      - name: Run unit tests
        uses: ./.github/workflows/units-tests-reusable.yml
        with:
          branch: ${{ steps.compute-branch.outputs.branch }}
          nodeVersion: ${{ inputs.nodeVersion }}
